name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  lint-go:
    name: 'Lint go'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

  checks:
    name: 'All checks passed'
    runs-on: ubuntu-latest
    needs:
      [
        lint-go
      ]
    steps:
      - name: End
        run: echo 'All checks done'
